// apps/web/src/routes/admin/properties/new/+page.svelte
<script lang="ts">
  import * as Content from "$lib/components/Content"
  import * as Section from "$lib/components/Section"
  import * as Formulary from "$lib/components/Formulary"
  import Button from "$lib/components/Button.svelte"
  import LocationInput from "$lib/components/LocationInput.svelte"
  import {
    get_property_type_label,
    PROPERTY_TYPE,
    type PropertyType,
  } from "$lib/property_type"
  import { get_property_destiny_label } from "$lib/property_destiny"
  import { compose_action } from "$lib/compose_action"
  import { ACTION } from "./actions/action"
  import type { PageData } from "./$types"

  let { data }: { data: PageData } = $props()

  let property_type = $state<PropertyType>(
    PROPERTY_TYPE.DEPARTMENT,
  )

  function handle_type_change(event: Event) {
    const target = event.currentTarget as HTMLSelectElement
    property_type = Number(target.value) as PropertyType
  }
</script>

{#snippet Location()}
  <section>
    <Section.Header>
      <Section.Title>ubicación</Section.Title>
    </Section.Header>
    <LocationInput />
  </section>
{/snippet}

{#snippet Characteristics()}
  <section>
    <Section.Header>
      <Section.Title>características</Section.Title>
    </Section.Header>
    <Formulary.Fields>
      <Formulary.Field>
        <Formulary.Label for="type">tipo</Formulary.Label>
        <Formulary.Select
          name="type"
          id="type"
          required
          onchange={handle_type_change}
        >
          {#each data.property_types as type}
            <option value={type}
              >{get_property_type_label(type)}</option
            >
          {/each}
        </Formulary.Select>
      </Formulary.Field>
      {#if property_type === PROPERTY_TYPE.DEPARTMENT}
        <Formulary.Field>
          <Formulary.Label for="unit"
            >unidad</Formulary.Label
          >
          <input
            placeholder="ej. 9A o 4011"
            required
            name="unit"
            id="unit"
            type="text"
          />
        </Formulary.Field>
      {/if}
    </Formulary.Fields>
  </section>
{/snippet}

{#snippet Destiny()}
  <section>
    <Section.Header>
      <Section.Title>destino</Section.Title>
    </Section.Header>
    <fieldset class="flex flex-col gap-2">
      {#each data.property_destinies as destiny}
        <label class="flex items-center gap-2">
          <input
            type="checkbox"
            name="destiny"
            value={destiny}
          />
          {get_property_destiny_label(destiny)}
        </label>
      {/each}
    </fieldset>
  </section>
{/snippet}

<Content.Root>
  <Content.Title>Creación de propiedad</Content.Title>
  <Content.Section>
    <Formulary.Root
      method="POST"
      action={compose_action(ACTION.CREATE_PROPERTY)}
    >
      <Formulary.Fields>
        {@render Location()}
        {@render Characteristics()}
        {@render Destiny()}
      </Formulary.Fields>
      <Formulary.Actions>
        <Button type="submit">Crear propiedad</Button>
      </Formulary.Actions>
    </Formulary.Root>
  </Content.Section>
</Content.Root>

// apps/web/app/routes/properties+/new.tsx
import { useState } from "react"
import { Form, redirect } from "react-router"
import { LocationInput } from "~/components/location_input"
import { require_auth } from "~/lib/auth.server"
import { error } from "~/lib/error.server"
import { has_edit_access } from "~/lib/property_access.server"
import type { Route } from "./+types/new"
import {
  get_property_type_label,
  PROPERTY_TYPE,
  type PropertyType,
} from "~/lib/property_type"
import { get_property_types } from "~/lib/property_type"
import {
  get_property_destinies,
  get_property_destiny_label,
} from "~/lib/property_destiny"
import * as actions from "./actions/index.server"

const INTENT = {
  CREATE_PROPERTY: "create_property",
} as const

export async function loader({
  request,
}: Route.LoaderArgs) {
  const { user } = await require_auth(request)
  if (!has_edit_access(user.accesses)) {
    throw error(400, "not found")
  }

  return {
    property_types: get_property_types(),
    property_destinies: get_property_destinies(),
  }
}

export async function action({
  request,
}: Route.ActionArgs) {
  const { user } = await require_auth(request)
  if (!has_edit_access(user.accesses)) {
    throw error(400, "not found")
  }
  const form_data = await request.formData()
  form_data.set("user_id", String(user.id))
  const intent = form_data.get("intent")
  if (!intent) {
    throw error(400, "intent is required")
  }
  switch (intent) {
    case INTENT.CREATE_PROPERTY: {
      const { redirect_to } =
        await actions.create_property(form_data)
      return redirect(redirect_to)
    }
  }
}

export default function ({
  loaderData,
}: Route.ComponentProps) {
  const { property_types, property_destinies } = loaderData
  const [disabled, set_disabled] = useState(true)
  const [property_type, set_property_type] =
    useState<PropertyType>(PROPERTY_TYPE.DEPARTMENT)
  return (
    <main>
      <h1>create property</h1>
      <section>
        <h2>ubicacion</h2>
        <Form method="POST">
          <input
            type="hidden"
            value={INTENT.CREATE_PROPERTY}
            name="intent"
          />
          <LocationInput
            on_selection={() => {
              set_disabled(false)
            }}
            on_clear={() => {
              set_disabled(true)
            }}
          />
          <p>
            <label htmlFor="type">tipo</label>
            <select
              name="type"
              id="type"
              required
              onChange={(event) => {
                const property_type = Number(
                  event.target.value,
                ) as PropertyType
                set_property_type(property_type)
              }}
            >
              {property_types.map((type) => {
                const id = `property_type_${type}`
                return (
                  <option key={id} value={type}>
                    {get_property_type_label(type)}
                  </option>
                )
              })}
            </select>
          </p>
          {property_type === PROPERTY_TYPE.DEPARTMENT ? (
            <p>
              <label htmlFor="unit">unidad</label>
              <input
                required
                name="unit"
                id="unit"
                type="text"
              />
            </p>
          ) : null}
          <fieldset>
            <legend>destino</legend>
            {property_destinies.map((destiny) => {
              const id = `destiny_${destiny}`
              return (
                <p key={id}>
                  <input
                    type="checkbox"
                    id={id}
                    name="destiny"
                    value={destiny}
                  />
                  <label htmlFor={id}>
                    {get_property_destiny_label(destiny)}
                  </label>
                </p>
              )
            })}
          </fieldset>
          <button disabled={disabled} type="submit">
            crear propiedad
          </button>
        </Form>
      </section>
    </main>
  )
}
