// apps/web/app/components/header.tsx
import { Form } from "react-router"
import "./header.css"
import { Button } from "~/components/button"
import type { Auth } from "~/lib/auth.server"

export function Header({ auth }: { auth: Auth }) {
  return (
    <header>
      <nav>
        {auth.user ? (
          <>
            <span>{auth.user.email}</span>
            <Form method="post" action="/auth/logout">
              <Button type="submit">
                Logout
              </Button>
            </Form>
          </>
        ) : (
          <Form method="post" action="/auth/google">
            <Button type="submit">Login</Button>
          </Form>
        )}
      </nav>
    </header>
  )
}

// apps/wev/src/lib/components/Header.svelte
<script lang="ts">
  import { base } from "$app/paths";
  import Button from "$lib/components/Button.svelte";

  interface Props {
    user: {
      id: number;
      email: string;
    } | null;
  }

  let { user }: Props = $props();
</script>

<header class="header">
  <nav class="header__nav">
    {#if user}
      <span class="header__email">{user.email}</span>
      <form method="POST" action="{base}/auth/logout">
        <Button type="submit">Logout</Button>
      </form>
    {:else}
      <form method="POST" action="{base}/auth/google">
        <Button type="submit">Login</Button>
      </form>
    {/if}
  </nav>
</header>

<style>
  .header {
    position: sticky;
    top: 0;
    z-index: 10;
    display: flex;
    justify-content: flex-end;
    align-items: center;
    padding: var(--spacing-4);
    height: var(--header-height);
    background-color: var(--gray-700);
  }

  .header__nav {
    display: flex;
    align-items: center;
    gap: var(--spacing-4);
  }

  .header__email {
    color: var(--gray-100);
    font-size: 0.875rem;
  }
</style>
